---

- name: "Update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "Upgrade packages"
  become: true
  apt:
    upgrade: yes


- name: "Remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: true

- name: "Install NodeJS and NPM "
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates a directory in EC2 instance
  become: true
  file:
    path: /home/ec2-user/backend_dir
    state: directory

# - name: Copying the articfact from local to EC2
#   ansible.builtin.unarchive:
#     src: artifact.tar.gz
#     dest: /home/ec2-user/backend_dir

- name: Copying the artifact from local to EC2
  become: true
  copy:
    src: artifact.tar.gz
    dest : /home/ec2-user/backend_dir/

- name: Uncompress Backend
  become: true
  shell: |
    cd /home/ec2-user/backend_dir
    tar xvzf artifact.tar.gz -C .
    
- name: Starting the app
  become: true
  shell: |
    cd /home/ec2-user/backend
    npm install
    pm2 stop default
    pm2 start npm -- start

# - name: Build package
#   shell: |
#     cd /home/ec2-user/backend
#     npm run build
#     cat .env
#     npm run prestart:prod
# - name: Start PM2
#   shell: |
#     cd /home/ec2-user/backend
#     pm2 stop default
#     pm2 start npm --name backend -- start
# - name: start pm2 for dist/main.js
#   become: no
#   shell: pm2 start main.js
#   args:
#     chdir: /home/ec2-user/backend/dist